repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        files: ^[^/]+$
    -   id: end-of-file-fixer
        files: ^[^/]+$
    -   id: check-yaml
        files: ^[^/]+$
    -   id: debug-statements
        files: ^[^/]+$
    -   id: double-quote-string-fixer
        files: ^[^/]+$
    -   id: name-tests-test
        files: ^[^/]+$
    -   id: requirements-txt-fixer
        files: ^[^/]+$
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    -   id: setup-cfg-fmt
        files: ^[^/]+$
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py39-plus, --add-import, 'from __future__ import annotations']
        files: ^[^/]+$
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        files: ^[^/]+$
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
        files: ^[^/]+$
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        files: ^[^/]+$
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        files: ^[^/]+$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
        additional_dependencies: [types-pyyaml]
        exclude: ^testing/resources/
        files: ^[^/]+$
